---
- name: symlink /usr/bin/python -> /usr/bin/python3
  hosts: "*"
  gather_facts: false
  tasks:
    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
      become: true

- include_tasks: download_maven.yml

- name: Install java
  apt:
    name: default-jre
    update_cache: yes
  become: true

- name: Copy application
  copy:
    src: "{{ artifact_name }}"
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create a service definition file
  copy:
    src: application.service
    dest:  /etc/systemd/system/
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: yes

- name: Start application
  service:
    name: application
    state: restarted
  become: true
